on:
  workflow_dispatch:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3

      - name: Hello world
        id: hello
        uses: casperklein/actiontest@master
        with:
          name: 'space'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Hello world (use default name)
        id: hello-default
        uses: casperklein/actiontest@master
